-- {-# LANGUAGE #-}
{-# OPTIONS_GHC -Wall #-}
----------------------------------------------------------------------
-- |
-- Module      :  Main
-- Copyright   :  (c) Conal Elliott 2010
-- License     :  BSD3
-- 
-- Maintainer  :  conal@conal.net
-- Stability   :  experimental
-- 
-- Trim the HTML generated by gitit to suit my WordPress blog
----------------------------------------------------------------------

module Main (main) where

import Data.List (isPrefixOf,tails)

main :: IO ()
main = interact (unlines . process . lines)

process :: [String] -> [String]
process = dropWhile (not . has "<!-- references -->")
        . tail  
        . takeWhile (not . has "<div id=\"footer\">")

has :: Eq a => [a] -> [a] -> Bool
has pat = any (pat `isPrefixOf`) . tails