flags: {}

extra-deps:
- gitit-0.12.3
# Swiped from gitit-0.12.3, since I'm going for consistency with
# the version of gitit I'm running.
- filestore-0.6.3.3
- recaptcha-0.1.0.3
- uri-0.1.6.4
- ConfigFile-1.1.4
- hoauth2-1.7.2
- url-2.1.3
- exceptions-0.8.3
- uri-bytestring-aeson-0.1.0.6
# "stack solver" says we don't need the following
# - aeson-1.3.1.1
# - skylighting-0.7.4
# - skylighting-core-0.7.4

# # Pandoc-2.5 (which we don't really need) and its requirements.
# # We could do without this section
# - pandoc-2.5
# - HsYAML-0.1.1.2
# - haddock-library-1.7.0
# - hslua-1.0.1
# - hslua-module-text-0.2.0

# resolver: lts-9.21  # ghc-8.0.2
# resolver: lts-11.22 # ghc-8.2.2
resolver: lts-12.14 # ghc-8.4.3
# resolver: lts-12.19 # ghc-8.4.4

# resolver: lts-14.4 # ghc-8.6.5
